name: Sync to Hugging Face hub
on:
  push:
    branches: [main] # Set to your default branch
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git rm -r --cached frontend/ || true
          git commit -m "Deploy to Hugging Face"
          git push --force https://theknight666:$HF_TOKEN@huggingface.co/spaces/theknight666/Eventa-Backend HEAD:main


