name: Sync to Hugging Face hub
on:
  push:
    branches: [main] # Set to your default branch
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # REPLACE 'your-hf-username/Eventa-Backend' with your actual Hugging Face username and Space name!
        run: git push --force https://user:$HF_TOKEN@huggingface.co/spaces/theknight666/Eventa-Backend main
